default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] %>

development:
  <<: *default
  database: task_management_tool_development
test:
  <<: *default
  database: task_management_tool_test
production:
  <<: *default
  database: task_management_tool_production
  username: task_management_tool
  password: <%= ENV["TASK_MANAGEMENT_TOOL_DATABASE_PASSWORD"] %>
